global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds.
  evaluation_interval: 15s  # Evaluate rules every 15 seconds.

scrape_configs:
  - job_name: 'golang-app'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['golang-app:8000']
